DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS album;
CREATE TABLE IF NOT EXISTS artist (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
followers INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS album (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
artist_id INTEGER NOT NULL,
tracks INTEGER NOT NULL,
FOREIGN KEY (artist_id) REFERENCES artist(id)
);
.import t1_artist.csv artist --csv
.import t1_album.csv album --csv

